### ISSUE TITLE
Error : TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by BorisVandermeer** [libai1943/CartesianPlanner#5]
Error output:
``` bash
Traceback (most recent call last):
  File ".../CartesianPlanner/script/reference_publisher.py", line 256, in <module>
    main()
  File ".../CartesianPlanner/script/reference_publisher.py", line 235, in main
    pickle.dump({"center": center_line, "static": static_obstacles, "dynamic": dynamic_obstacles}, f)
TypeError: write() argument must be str, not bytes
```

For Python 3.x.x，should be changed to open in binary read-write mode(' wb+') at line 234 in "/script/reference_publisher.py" .

``` C++
//original code
with open(pickle_path, 'w') as f:

//changed code for python 3.x.x
with open(pickle_path, 'wb') as f:

```

**Comment by yakunouyang** [comment]
fixed, thanks for your kind notice!
